.TH freeguide "1" "November 2003" "freeguide 0.7.2" "User Commands"
.SH NAME
freeguide \- display TV listings
.SH SYNOPSIS
.B freeguide
.br
.B java \fI-jar /usr/share/java/FreeGuide.jar\fR
.SH DESCRIPTION
Display TV listings.
.SH AUTHOR
Written by Andy Balaam.

This manual page was written by Shaun Jackman <sjackman@debian.org>
for the Debian system.
.SH "REPORTING BUGS"
Report bugs to <freeguide-tv-devel@lists.sourceforge.net>.
.SH COPYRIGHT
Copyright 2001-2003 by Andy Balaam and the FreeGuide contributors

This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
http://sourceforge.net/projects/freeguide-tv/
