/*
 * FreeGuide J2
 *
 * Copyright (c) 2001 by Andy Balaam
 *
 * Released under the GNU General Public License
 * with ABSOLUTELY NO WARRANTY.
 *
 * See the file COPYING for more information.
 */

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collections;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextArea;
import javax.swing.text.JTextComponent;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParserFactory;
import javax.xml.parsers.SAXParser;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

/**
 * A form that displays and prints TV listings.
 *
 * @author  Andy Balaam
 * @version 11
 */
public class FreeGuideViewer extends javax.swing.JFrame implements FreeGuideLauncher, FreeGuideSAXInterface {

    public FreeGuideViewer(FreeGuideLauncher newLauncher) {
		
		launcher = newLauncher;
		
		doingProgs = false;
		dontDownload = false;
		
		// Set up UI
        initComponents();
		
		// Set the date to today
		theDate = GregorianCalendar.getInstance();
		
		// Set up custom UI elements
		initMyComponents();
		
		// Draw the programmes on the screen
        updatePanel();

    }

	private void updatePanel() {
		
		FreeGuide.prefs.flushAll();
		
		// Find what channels the user has chosen
		getSelectedChannels();

		// Load the data
		loadProgrammeData();
	
		
		
		// Error if we're missing programme info
		if(missingFiles) {
			
			if(dontDownload) {
				
				// Clear the screen if we're not supposed to download
				innerPanel.removeAll();
				setVisible(true);
				
			} else {
			
				String msg = "There are missing listings for this day.\n"+
					"Do you want to download more?";
				
				int	r = JOptionPane.showConfirmDialog(this, msg, "Download listings?", JOptionPane.YES_NO_OPTION );
			
				if(r==0) {
				
					downloadListings();
				
				} else {
					
					// Clear the screen if we're not supposed to downlaod
					innerPanel.removeAll();
					setVisible(true);
					
				}
				
				dontDownload = true;
				
			}

		} else {
			
			drawProgrammes();
			updatePrintedGuide();
			setVisible(true);
			
		}
		
    }
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        popProg = new javax.swing.JPopupMenu();
        menAddFav = new javax.swing.JMenuItem();
        topPanel = new javax.swing.JPanel();
        butGoToNow = new javax.swing.JButton();
        butPrev = new javax.swing.JButton();
        comTheDate = new javax.swing.JComboBox();
        butNext = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        printedGuideScrollPane = new javax.swing.JScrollPane();
        printedGuideArea = new javax.swing.JEditorPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        channelNameScrollPane = new javax.swing.JScrollPane();
        channelNamePanel = new javax.swing.JPanel();
        outerPanel = new javax.swing.JPanel();
        innerScrollPane = new javax.swing.JScrollPane();
        innerPanel = new javax.swing.JPanel();
        timeScrollPane = new javax.swing.JScrollPane();
        timePanel = new FreeGuideTimePanel();
        bottomPanel = new javax.swing.JPanel();
        butPrint = new javax.swing.JButton();
        topLeftPanel = new javax.swing.JPanel();
        butRevertFavs = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menPrint = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        menQuit = new javax.swing.JMenuItem();
        actionsMenu = new javax.swing.JMenu();
        menDownload = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        menFavourites = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        menCustomiser = new javax.swing.JMenuItem();
        menChannels = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menOptions = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        menUserGuide = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        menAbout = new javax.swing.JMenuItem();

        menAddFav.setText("Add to Favourites");
        menAddFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAddFavActionPerformed(evt);
            }
        });

        popProg.add(menAddFav);

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("FreeGuide J2 " + FreeGuide.getVersion());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        topPanel.setLayout(new java.awt.GridBagLayout());

        butGoToNow.setFont(new java.awt.Font("Dialog", 0, 10));
        butGoToNow.setText("Go To Now");
        butGoToNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGoToNowActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        topPanel.add(butGoToNow, gridBagConstraints);

        butPrev.setText("-");
        butPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPrevActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        topPanel.add(butPrev, gridBagConstraints);

        comTheDate.setEditable(true);
        comTheDate.setMinimumSize(new java.awt.Dimension(150, 25));
        comTheDate.setPreferredSize(new java.awt.Dimension(150, 25));
        comTheDate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comTheDateItemStateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        topPanel.add(comTheDate, gridBagConstraints);

        butNext.setText("+");
        butNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNextActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        topPanel.add(butNext, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        getContentPane().add(topPanel, gridBagConstraints);

        splitPane.setDividerLocation(180);
        splitPane.setDividerSize(5);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        printedGuideArea.setEditable(false);
        printedGuideArea.setContentType("text/html");
        printedGuideScrollPane.setViewportView(printedGuideArea);

        splitPane.setRightComponent(printedGuideScrollPane);

        jSplitPane1.setDividerSize(5);
        channelNameScrollPane.setBorder(null);
        channelNameScrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        channelNameScrollPane.setMinimumSize(new java.awt.Dimension(100, 100));
        channelNameScrollPane.setPreferredSize(new java.awt.Dimension(100, 100));
        channelNamePanel.setLayout(null);

        channelNamePanel.setBackground(new java.awt.Color(245, 245, 255));
        channelNameScrollPane.setViewportView(channelNamePanel);

        jSplitPane1.setLeftComponent(channelNameScrollPane);

        outerPanel.setLayout(new java.awt.GridBagLayout());

        outerPanel.setBackground(new java.awt.Color(245, 245, 255));
        innerScrollPane.setBorder(null);
        innerPanel.setLayout(null);

        innerPanel.setBackground(new java.awt.Color(245, 245, 255));
        innerScrollPane.setViewportView(innerPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 0.9;
        outerPanel.add(innerScrollPane, gridBagConstraints);

        timeScrollPane.setBorder(null);
        timeScrollPane.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        timeScrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        timeScrollPane.setMaximumSize(new java.awt.Dimension(24, 24));
        timeScrollPane.setMinimumSize(new java.awt.Dimension(24, 24));
        timeScrollPane.setPreferredSize(new java.awt.Dimension(24, 24));
        timePanel.setLayout(null);

        timePanel.setBackground(new java.awt.Color(245, 245, 255));
        timeScrollPane.setViewportView(timePanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        outerPanel.add(timeScrollPane, gridBagConstraints);

        jSplitPane1.setRightComponent(outerPanel);

        splitPane.setLeftComponent(jSplitPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(splitPane, gridBagConstraints);

        butPrint.setFont(new java.awt.Font("Dialog", 0, 10));
        butPrint.setText("Print this personalised listing...");
        butPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPrintActionPerformed(evt);
            }
        });

        bottomPanel.add(butPrint);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(bottomPanel, gridBagConstraints);

        butRevertFavs.setFont(new java.awt.Font("Dialog", 0, 10));
        butRevertFavs.setText("Show Favourites Only");
        butRevertFavs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRevertFavsActionPerformed(evt);
            }
        });

        topLeftPanel.add(butRevertFavs);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(topLeftPanel, gridBagConstraints);

        fileMenu.setText("File");
        menPrint.setText("Print Listing");
        menPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPrintActionPerformed(evt);
            }
        });

        fileMenu.add(menPrint);
        fileMenu.add(jSeparator5);
        menQuit.setText("Quit");
        menQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menQuitActionPerformed(evt);
            }
        });

        fileMenu.add(menQuit);
        jMenuBar2.add(fileMenu);
        actionsMenu.setText("Actions");
        menDownload.setText("Download Listings...");
        menDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menDownloadActionPerformed(evt);
            }
        });

        actionsMenu.add(menDownload);
        actionsMenu.add(jSeparator3);
        menFavourites.setText("Choose Favourites...");
        menFavourites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menFavouritesActionPerformed(evt);
            }
        });

        actionsMenu.add(menFavourites);
        jMenuBar2.add(actionsMenu);
        optionsMenu.setText("Tools");
        menCustomiser.setText("Customise...");
        menCustomiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCustomiserActionPerformed(evt);
            }
        });

        optionsMenu.add(menCustomiser);
        menChannels.setText("Choose Channels...");
        menChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menChannelsActionPerformed(evt);
            }
        });

        optionsMenu.add(menChannels);
        optionsMenu.add(jSeparator1);
        menOptions.setText("Options...");
        menOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOptionsActionPerformed(evt);
            }
        });

        optionsMenu.add(menOptions);
        jMenuBar2.add(optionsMenu);
        helpMenu.setText("Help");
        menUserGuide.setText("User Guide...");
        menUserGuide.setEnabled(false);
        helpMenu.add(menUserGuide);
        helpMenu.add(jSeparator4);
        menAbout.setText("About...");
        menAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAboutActionPerformed(evt);
            }
        });

        helpMenu.add(menAbout);
        jMenuBar2.add(helpMenu);
        setJMenuBar(jMenuBar2);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(615, 345));
        setLocation((screenSize.width-615)/2,(screenSize.height-345)/2);
    }//GEN-END:initComponents

	private void menChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menChannelsActionPerformed
		setVisible(false);
		new FreeGuideChannelsChooser(this).setVisible(true);
		dispose();
	}//GEN-LAST:event_menChannelsActionPerformed

	private void menCustomiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCustomiserActionPerformed
		setVisible(false);
		new FreeGuideCustomiser(this).setVisible(true);
		dispose();
	}//GEN-LAST:event_menCustomiserActionPerformed

	private void menAddFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAddFavActionPerformed
		
		// Make a favourite
		FreeGuideFavourite fav = new FreeGuideFavourite();
		String title = rightClickedProg.getTitle();
		fav.setTitleString( title );
		fav.setName( title );
		
		// Remember the favourite
		FreeGuide.prefs.favourites.appendFreeGuideFavourite(fav);
		
		// Tick this programme
		JLabel txt = getJLabelFromProg(rightClickedProg);
		//FreeGuideProgramme prog = getProgFromJLabel(txt);
		
		txt.setBackground( FreeGuide.prefs.screen.getColor("programme_chosen_colour", FreeGuide.PROGRAMME_CHOSEN_COLOUR) );
		tickedProgrammes.add(rightClickedProg);
			
		FreeGuide.prefs.addChoice(rightClickedProg);
			
		// Update the guide
		updatePrintedGuide();
		
	}//GEN-LAST:event_menAddFavActionPerformed

	private void butRevertFavsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRevertFavsActionPerformed
		
		// Untick everything
		for(int i=0;i<tickedProgrammes.size();i++) {
			FreeGuide.prefs.removeChoice( (FreeGuideProgramme)tickedProgrammes.get(i) );
		}
		
		// Tell the prefs we've got no choices for today
		FreeGuide.prefs.chosenSomething( theDate, false );
		
		// Clear out the vector of ticked programmes
		tickedProgrammes.clear();
		
		// Tick favourites
		tickFavsOrChoices();
		updatePrintedGuide();
		
	}//GEN-LAST:event_butRevertFavsActionPerformed

	private void comTheDateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comTheDateItemStateChanged
		
		updateIfDateChanged();
			
	}//GEN-LAST:event_comTheDateItemStateChanged

	private void menPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPrintActionPerformed
		
		writeOutAsHTML();
		
	}//GEN-LAST:event_menPrintActionPerformed

	private void butGoToNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGoToNowActionPerformed
		
		goToNow();
		
	}//GEN-LAST:event_butGoToNowActionPerformed

	private void menAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAboutActionPerformed
		
		new FreeGuideAbout(this, true).setVisible(true);
		
	}//GEN-LAST:event_menAboutActionPerformed

	private void menUserGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menUserGuideActionPerformed
		
		
		
	}//GEN-LAST:event_menUserGuideActionPerformed

	private void menOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOptionsActionPerformed
		
		setVisible(false);
		new FreeGuideOptionsWizard(this).setVisible(true);
		dispose();
		
	}//GEN-LAST:event_menOptionsActionPerformed

	private void menFavouritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menFavouritesActionPerformed
				
		setVisible(false);
		new FreeGuideFavouritesList(this).setVisible(true);
		dispose();
		
	}//GEN-LAST:event_menFavouritesActionPerformed

	private void menDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menDownloadActionPerformed
		
		downloadListings();
		
	}//GEN-LAST:event_menDownloadActionPerformed

	private void downloadListings() {
		FreeGuideUtils.execAndWait(FreeGuide.prefs.getCommands("tv_grab"), "Downloading", this);
	}
	
	private void menQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menQuitActionPerformed
		
		quit();
		
	}//GEN-LAST:event_menQuitActionPerformed

	private void butPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPrintActionPerformed
		
		writeOutAsHTML();
		
	}//GEN-LAST:event_butPrintActionPerformed

	private void butNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNextActionPerformed
		
		Calendar tmpDate = GregorianCalendar.getInstance();
		tmpDate.setTimeInMillis( theDate.getTimeInMillis() );

		tmpDate.add( Calendar.DAY_OF_YEAR, 1 );
		
		String datestr = comboBoxDateFormat.format(tmpDate.getTime());
		
		comTheDate.setSelectedItem(datestr);
		
	}//GEN-LAST:event_butNextActionPerformed

	private void butPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPrevActionPerformed
		
		Calendar tmpDate = GregorianCalendar.getInstance();
		tmpDate.setTimeInMillis( theDate.getTimeInMillis() );

		tmpDate.add( Calendar.DAY_OF_YEAR, -1 );

		String datestr = comboBoxDateFormat.format(tmpDate.getTime());

		comTheDate.setSelectedItem(datestr);
		
	}//GEN-LAST:event_butPrevActionPerformed

	private void addInnerScrollPaneAdjustmentListeners() {
		
		innerScrollPane.getHorizontalScrollBar().addAdjustmentListener(new java.awt.event.AdjustmentListener() {
			public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
				innerScrollPaneHorAdjust(evt);
			}
		});
	
		innerScrollPane.getVerticalScrollBar().addAdjustmentListener(new java.awt.event.AdjustmentListener() {
			public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
				innerScrollPaneVerAdjust(evt);
			}
		});
	}
	
	private void removeInnerScrollPaneAdjustmentListeners() {
		
		java.awt.event.AdjustmentListener[] l = innerScrollPane.getHorizontalScrollBar().getAdjustmentListeners();
		for(int i=0;i<l.length;i++) {
			innerScrollPane.getHorizontalScrollBar().removeAdjustmentListener(l[i]);
		}
		
		l = innerScrollPane.getVerticalScrollBar().getAdjustmentListeners();
		for(int i=0;i<l.length;i++) {
			innerScrollPane.getVerticalScrollBar().removeAdjustmentListener(l[i]);
		}
		
	}
	
	/**
	 * Add listeners to the two scrollbars in the GUI and put the relevant
	 * dates in the date list
	 */
    private void initMyComponents() {
		
		//  Do the listeners
		addInnerScrollPaneAdjustmentListeners();

		// Make the dates list
		Calendar tmpDate = GregorianCalendar.getInstance();
		tmpDate.setTimeInMillis( theDate.getTimeInMillis() );
		
		for(int i=0;i<14;i++) {
			
			comTheDate.addItem(comboBoxDateFormat.format(tmpDate.getTime()));
			tmpDate.add( Calendar.DAY_OF_YEAR, 1 );
			
		}
		
		// Choose the current date
		String datestr = comboBoxDateFormat.format(theDate.getTime());
		comTheDate.setSelectedItem(datestr);
	
		/*JMenuItem menuItem;
		popProg = new JPopupMenu();
		menuItem = new JMenuItem("A popup menu item");
		//menuItem.addActionListener(this);
		popProg.add(menuItem);
		menuItem = new JMenuItem("Another popup menu item");
		//menuItem.addActionListener(this);
		popProg.add(menuItem);*/
		
    }//initMyComponents
    
	private void goToNow() {
	
		comTheDate.setSelectedIndex(0);
		
		int tmpScr = timePanel.getNowScroll();
		
		timeScrollPane.getHorizontalScrollBar().setValue(tmpScr);
		innerScrollPane.getHorizontalScrollBar().setValue(tmpScr);
		
	}
	
	/**
	 * The event procedure for the horizontal scrollpane listener - just
	 * calls the scrollTime method.
	 */
    private void innerScrollPaneHorAdjust(java.awt.event.AdjustmentEvent evt) {
		scrollTime();
    }//innerScrollPaneHorAdjust
    
	/**
	 * The event procedure for the vertical scrollpane listener - just
	 * calls the scrollChannelNames method.
	 */
    private void innerScrollPaneVerAdjust(java.awt.event.AdjustmentEvent evt) {
		scrollChannelNames();
    }//innerScrollPaneVerAdjust
    
	/**
	 * The event listener for the form closing event - calls the quit method
	 */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        quit();
    }//GEN-LAST:event_exitForm

	/**
	 * Quits the program.
	 */
	private void quit() {
		
		// Delete old .fgd files
		// ---------------------
		
		String fs = System.getProperty("file.separator");
		
		// Get the date last week
		Calendar lastWeek = GregorianCalendar.getInstance();
		lastWeek.add(Calendar.WEEK_OF_YEAR, -1);
		Calendar cal = GregorianCalendar.getInstance();
		
		File wd = new File(FreeGuide.prefs.performSubstitutions(FreeGuide.prefs.misc.get("working_directory")));
		String[] files = wd.list();
		for(int i=0;i<files.length;i++) {
			// If it's a fgd file, we may want to delete it
			if(files[i].endsWith(".fgd")) {
				int len = files[i].length();
				String dateStr = files[i].substring(len-12, len-4);
				try {
					cal.setTime( fileDateFormat.parse(dateStr) );
					if(cal.before(lastWeek)) {
						new File(wd + fs + files[i]).delete();
					}
				} catch(java.text.ParseException e) {
					e.printStackTrace();
				}
			}
		}
		
		// Delete old entries in choices preferences
		Calendar[] choiceDates = FreeGuide.prefs.getAllChosenDays();
		for(int i=0;i<choiceDates.length;i++) {
			if(choiceDates[i].before(lastWeek)) {
				FreeGuide.prefs.chosenSomething(choiceDates[i], false);
			}
		}
		
		// Exit
		// ----
		System.exit(0);
		
	}//quit
     
	/**
	 * Loads the programme data from a file and stores it in a class
	 * structure ready for display on the screen.
	 */
    private void loadProgrammeData() {
		
		String fs = System.getProperty("file.separator");
		
		// Are we missing any channel files?
		missingFiles = false;
		
		// Find the day's start and end
		FreeGuideTime divideTime = FreeGuide.prefs.misc.getFreeGuideTime("day_start_time");
		earliest = GregorianCalendar.getInstance();
		earliest.setTimeInMillis( theDate.getTimeInMillis() );
		divideTime.adjustCalendar(earliest);
		latest = GregorianCalendar.getInstance();
		latest.setTimeInMillis( theDate.getTimeInMillis() );
		latest.add( Calendar.DAY_OF_YEAR, 1);
		divideTime.adjustCalendar(latest);
		
		programmes = new Vector();
		
		for(int curChan=0;curChan<channelNames.length;curChan++) {
		        
			String wkDir = FreeGuide.prefs.performSubstitutions(FreeGuide.prefs.misc.get("working_directory"));
	
			String datestr = fileDateFormat.format(theDate.getTime());
	
			String xmlFilename = wkDir+fs+channelIDs[curChan]+"-"+datestr+".fgd";
			
			if((new File(xmlFilename).exists())) {	// If the file exists
				
				FreeGuide.log.info("Opening programmes file "+xmlFilename);
				
				// Load it into memory and process it
				try {//ParserExceptions etc
	    
					DefaultHandler handler = new FreeGuideSAXHandler(this);
					SAXParserFactory factory = SAXParserFactory.newInstance();
					
					SAXParser saxParser = factory.newSAXParser();
		
					doingProgs=true;
		
					// Will be a different name for each channel and whatever
					// date we're on obviously
					saxParser.parse(xmlFilename, handler);
					
					doingProgs=false;
	    
				} catch(ParserConfigurationException e) {
					e.printStackTrace();
				} catch(SAXException e) {
					e.printStackTrace();
				} catch(java.io.IOException e) {
					e.printStackTrace();
				}//try
				
			} else { // If no file exists
				
				// Do nothing because no file exists
	    
				FreeGuide.log.warning("Listings file not found: "+xmlFilename);
				
				missingFiles = true;
				
			}//if
			
		}//for
		
	}//loadProgrammeData
    
	/**
	 * Given the programme, returns the jlabel displaying it.
	 *
	 * @param prg the FreeGuideProgramme for a programme
	 * @returns  the programme referred to
	 */
	private JLabel getJLabelFromProg(FreeGuideProgramme prg) {
		int i = programmes.indexOf(prg);
		return (JLabel)textAreas.get(i);
	}//getJLabelFromPrpg
	
	/**
	 * Given the JLabel displaying it, returns the programme.
	 *
	 * @param bx the JLabel for a programme
	 * @returns  the programme referred to
	 */
	private FreeGuideProgramme getProgFromJLabel(JLabel bx) {
		int i = textAreas.indexOf(bx);
		return (FreeGuideProgramme)programmes.get(i);
	}//getProgFromJLabel

	/**
	 * The event procedure for a JLabel when it is clicked.
	 */
	private void jLabelClicked(java.awt.event.MouseEvent evt) {
		
		JLabel txt = (JLabel)evt.getSource();
		FreeGuideProgramme prog = getProgFromJLabel(txt);
		
		// Find out whether this is ticked
		if(tickedProgrammes.contains(prog)) {
			// Remove from ticked list

			txt.setBackground( FreeGuide.prefs.screen.getColor("programme_normal_colour", FreeGuide.PROGRAMME_NORMAL_COLOUR) );
			tickedProgrammes.remove(prog);
			
			FreeGuide.prefs.removeChoice(prog);
			
		} else {
			// Add to ticked list
			
			txt.setBackground( FreeGuide.prefs.screen.getColor("programme_chosen_colour", FreeGuide.PROGRAMME_CHOSEN_COLOUR) );
			tickedProgrammes.add(prog);
			
			FreeGuide.prefs.addChoice(prog);
			
		}
		
		updatePrintedGuide();
		
	}
    
	/**
	 * Scrolls the time panel to the same x-position as the main panel.
	 */
    private void scrollTime() {
		timeScrollPane.getHorizontalScrollBar().setValue(innerScrollPane.getHorizontalScrollBar().getValue());
    }//scrollTime
    
	/**
	 * Scrolls the channel names to the same y-position as the main panel.
	 */
    private void scrollChannelNames() {
		channelNameScrollPane.getVerticalScrollBar().setValue(innerScrollPane.getVerticalScrollBar().getValue());	
    }//scrollChannelNames
    
	/**
	 * Does the main work of displaying the stored programmes on screen.
	 */
	private void drawProgrammes() {
		
		String lineBreak = System.getProperty("line.separator");
		
		// Read in viewing options
		int channelHeight = FreeGuide.prefs.screen.getInt("channel_height", FreeGuide.CHANNEL_HEIGHT);
		int halfVerGap = FreeGuide.prefs.screen.getInt("vertical_gap", FreeGuide.VERTICAL_GAP);
		int halfHorGap = FreeGuide.prefs.screen.getInt("horizontal_gap", FreeGuide.HORIZONTAL_GAP);
		int panelWidth = FreeGuide.prefs.screen.getInt("panel_width",FreeGuide.PANEL_WIDTH);
		
		int channelPanelWidth = FreeGuide.prefs.screen.getInt("channel_panel_width", FreeGuide.CHANNEL_PANEL_WIDTH);

		// Delete all the old textareas
		innerPanel.removeAll();
		
		int tmpH = channelIDs.length*channelHeight;
		innerPanel.setPreferredSize(new java.awt.Dimension(panelWidth, tmpH));
		innerPanel.setMinimumSize(new java.awt.Dimension(panelWidth, tmpH));
		innerPanel.setMaximumSize(new java.awt.Dimension(panelWidth, tmpH));
		
		tmpH = timePanel.getPreferredSize().height;
		timePanel.setPreferredSize(new java.awt.Dimension(panelWidth, tmpH));
		timePanel.setMinimumSize(new java.awt.Dimension(panelWidth, tmpH));
		timePanel.setMaximumSize(new java.awt.Dimension(panelWidth, tmpH));
		
		Color channelColour = FreeGuide.prefs.screen.getColor("channel_colour", FreeGuide.CHANNEL_COLOUR);

		channelNamePanel.removeAll();
		
		textAreas = new Vector();	// Vector to store all the textareas
		tickedProgrammes = new Vector();	// And whether they'return ticked
	
		// Temporal width in millisecs
		long temporalWidth = latest.getTimeInMillis()-earliest.getTimeInMillis();
	
		// Find the multiplier to help us position programmes
		double widthMultiplier = (double)panelWidth/(double)temporalWidth;
	
		channelNamePanel.setPreferredSize(new Dimension(channelPanelWidth, channelIDs.length*channelHeight+50));
	
		for(int c=0;c<channelIDs.length;c++) {
			
			JLabel ctxt = new JLabel(channelNames[c]);
			ctxt.setBounds(0, timeScrollPane.getHeight()+(halfVerGap*2)+(c*channelHeight)-1, channelNamePanel.getPreferredSize().width-1, channelHeight-(halfVerGap*4));
	    
		    ctxt.setBackground(channelColour);
			ctxt.setFont(new java.awt.Font("Dialog", 1, 12));
			ctxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
			ctxt.setHorizontalAlignment(JLabel.LEFT);
			ctxt.setOpaque(true);
		
			channelNamePanel.add(ctxt);
			
		}
		
		for(int p=0;p<programmes.size();p++) {
	    
			FreeGuideProgramme prog = (FreeGuideProgramme)programmes.get(p);
			
			Calendar st = prog.getStart();
			Calendar ed = prog.getEnd();
		
			String progDesc = prog.getDesc();
			String progTitle = prog.getTitle();
			
			// Find the channel number
			String channelID = prog.getChannelID();
			Vector tmpChannelIDs = new Vector();
			tmpChannelIDs.addAll(Arrays.asList(channelIDs));
			int ch = tmpChannelIDs.indexOf(channelID);
			
			if(ch == -1) {
				FreeGuide.log.severe("Channel ID " + channelID + "not found when drawing channels.");
			}
			
			JLabel txt = new JLabel(timeFormat.format(st.getTime())+ " " + progTitle);
			
			textAreas.add(txt);
			
			// FEATURE: option to add editor pane styled text with description
			//JEditorPane txt = new JEditorPane("text/html", "    " + fmt.format(st)+ " " + prog.getTitle() + lineBreak + prog.getDesc());
				
			if( progDesc == null ) {
				txt.setToolTipText(progTitle);
			} else {
				txt.setToolTipText(progTitle + " - " + progDesc);
			}
		
			int left = halfHorGap+(int)((st.getTimeInMillis()-earliest.getTimeInMillis())*widthMultiplier);
			int right = ((int)((ed.getTimeInMillis()-earliest.getTimeInMillis())*widthMultiplier)) - (halfHorGap*2);
			int top = halfVerGap+(ch*channelHeight);
			int bottom = ((ch+1)*channelHeight)-(halfVerGap*2);

			//txt.setLineWrap(true);
			
			txt.setFont(new java.awt.Font("Dialog", 0, 10));
			txt.setBorder(new javax.swing.border.LineBorder(Color.black));
			txt.setOpaque(true);
			
			txt.setBounds(left, top, right-left, bottom-top);

			
			
			txt.addMouseListener(new java.awt.event.MouseListener() {
				public void mouseClicked(java.awt.event.MouseEvent evt) {
					jLabelClicked(evt);
				}
				public void mousePressed(java.awt.event.MouseEvent evt) {
					maybeShowPopup(evt);
				}
				public void mouseReleased(java.awt.event.MouseEvent evt) {
					maybeShowPopup(evt);
				}
				public void mouseEntered(java.awt.event.MouseEvent evt) {}
				public void mouseExited(java.awt.event.MouseEvent evt) {}
				private void maybeShowPopup(java.awt.event.MouseEvent evt) {
					if (evt.isPopupTrigger()) {
						rightClickedProg = getProgFromJLabel((JLabel)evt.getSource());
						popProg.show(evt.getComponent(), evt.getX(), evt.getY());
					}
				}
			});

			innerPanel.add(txt);
			
		}//for
		
		tickFavsOrChoices();
				
		timePanel.setTimes(earliest, latest);
		
		timePanel.revalidate();
		timePanel.repaint();
		
		innerPanel.revalidate();
		innerPanel.repaint();
		
		channelNamePanel.revalidate();
		channelNamePanel.repaint();
		
	}//drawChannels
	
	/**
	 * Shade those boxes that are favourite programmes or have been chosen.
	 */
	private void tickFavsOrChoices() {
		
		// Get whether the user's choice for today or null for none
		Vector choices = FreeGuide.prefs.getChosenProgs(theDate);
		
		// Get the colours we need
		Color tickedColour = FreeGuide.prefs.screen.getColor("programme_chosen_colour", FreeGuide.PROGRAMME_CHOSEN_COLOUR);
		Color nonTickedColour = FreeGuide.prefs.screen.getColor("programme_normal_colour", FreeGuide.PROGRAMME_NORMAL_COLOUR);
		
		for(int p=0;p<programmes.size();p++) {
	    
			// Get the programme and textarea we'return talking about
			FreeGuideProgramme prog = (FreeGuideProgramme)programmes.get(p);
			JLabel txt = (JLabel)textAreas.get(p);
			
			// Have we already got choices for today?
			if(choices!=null) {
				// Yes, use those choices
						
				for(int i=0;i<choices.size();i++) {
					
					if(choices.get(i).equals(prog)) {
						txt.setBackground(tickedColour);
						tickedProgrammes.add(prog);
						break;
					} else {
						txt.setBackground(nonTickedColour);
					}
					
				}
				
			} else {
				// No, use the favourites
			
				// Check if this is a favourite and tick it if so
				FreeGuideFavourite[] favourites = FreeGuide.prefs.getFavourites();
				if(favourites!=null) {
					
					boolean unticked = true;
					for(int i=0;i<favourites.length;i++) {
						
						if(favourites[i].matches(prog)) {
							// Remember this as a choice for next time
							FreeGuide.prefs.addChoice(prog);
				
							txt.setBackground(tickedColour);
							tickedProgrammes.add(prog);
							unticked = false;
							break;
						}
						
					}//for		
					if(unticked){
						txt.setBackground(nonTickedColour);
					}
				}//if
			}//if
			
		}//for
		
	}
	
	private void updateIfDateChanged() {
		
		if(!doingProgs && !comboBoxDateFormat.format(theDate.getTime()).equals((String)comTheDate.getSelectedItem())) {
		
			try {
			
				theDate.setTime( comboBoxDateFormat.parse((String)comTheDate.getSelectedItem()) );
			
			} catch(java.text.ParseException e) {
			
				e.printStackTrace();
			
			}//try

			updatePanel();
		
		}//if
		
	}
    
	// ------------------------------------------------------------------------
	// HMTL Guide stuff
	
    private void updatePrintedGuide() {

		printedGuideArea.setText(constructHTMLGuide(true));
	
    }
    
	/*
	 * Saves out the listings as an HTML file to be printed.
	 */
	private void writeOutAsHTML() {

		String fs = System.getProperty("file.separator");
		
		// Make a file in the default location
		File f = new File(FreeGuide.prefs.performSubstitutions(FreeGuide.prefs.misc.get("working_directory")+fs+"guide.html"));
		
		try {//IOException
			
			BufferedWriter buffy = new BufferedWriter(new FileWriter(f));

			buffy.write(constructHTMLGuide(false));

			buffy.close();
			
			String[] cmds = FreeGuideUtils.substitute(FreeGuide.prefs.commandline.getStrings("browser_command"), "%filename%", f.getPath());
			FreeGuideUtils.execNoWait(cmds);

		
		} catch(java.io.IOException e) {
			e.printStackTrace();
		}//try
		
	}//writeOutAsHTML
	
	/**
	 * Makes a TV Guide in HTML format and returns it as a string.
	 *
	 * @return the TV guide as a string of html
	 */
	private String constructHTMLGuide(boolean onScreen) {
		
		// The string we shall return
		String ans = "";
		
		// Set up some constants
		String lineBreak = System.getProperty("line.separator");

		ans+="<html>"+lineBreak;
		ans+="<head>"+lineBreak;
		ans+="  <title>TV Guide for "+htmlDateFormat.format(theDate.getTime())+"</title>"+lineBreak;
		ans+="  <link rel='StyleSheet' href='"+FreeGuide.prefs.performSubstitutions(FreeGuide.prefs.misc.get("css_file"))+"' type='text/css'>"+lineBreak;
		ans+="</head>"+lineBreak;
		ans+="<body>"+lineBreak;
		ans+="  <h1>";
		
		if(onScreen) {
			ans+="<font face='helvetica, helv, arial, sans serif' size=4>";
			ans+="Your Personalised TV Guide for "+htmlDateFormat.format(theDate.getTime());
			ans+="</font>";
		} else {
			ans+="TV Guide for "+htmlDateFormat.format(theDate.getTime());
		}
		
		ans+="</h1>"+lineBreak;

		if(onScreen) {
			ans+="<font face='helvetica, helv, arial, sans serif' size=3>";
			ans+="<p>Select programmes above by clicking on them, and they will turn grey and appear below.</p>";
			ans+="</font>";
		}
		
		// Sort the programmes
		Collections.sort(tickedProgrammes, new FreeGuideProgrammeStartTimeComparator());

		// Add them to the HTML list
		// ----------------------------

		if(onScreen) {ans+="<font face='helvetica, helv, arial, sans serif' size=3>";}
		
		for(int i=0;i<tickedProgrammes.size();i++) {

			FreeGuideProgramme prog = (FreeGuideProgramme)tickedProgrammes.get(i);

			//fmt = new SimpleDateFormat("HH:mm");
    
			if(prog.getDesc() == null) {
				ans+="  <p><b>"+timeFormat.format(prog.getStart().getTime())+" - "+prog.getTitle()+"</b><br>"+prog.getChannelName()+", ends "+timeFormat.format(prog.getEnd().getTime())+"</p>"+lineBreak;
			} else {
				ans+="  <p><b>"+timeFormat.format(prog.getStart().getTime())+" - "+prog.getTitle()+"</b><br>"+prog.getChannelName()+", ends "+timeFormat.format(prog.getEnd().getTime())+"<br>"+prog.getDesc()+"</p>"+lineBreak;
			}
    
		}//for

		if(onScreen) {ans+="</font>";}
		
		if(!onScreen) {
		
			ans+="<hr>"+lineBreak;
			ans+="<address>";
			ans+="http://freeguide-tv.sourceforge.net";
			ans+="</address>"+lineBreak;
			
		}
			
		ans+="</body>"+lineBreak;
		ans+="</html>"+lineBreak;

		return ans;
		
	}
	
	//------------------------------------------------------------------------
	// XML stuff
	
    public void startDocument() {  
		saxLoc = new String();
	}//startDocument
    
    public void endDocument() {
		saxLoc=null;
    }//endDocument
    
    public void startElement(String name, org.xml.sax.Attributes attrs) {
		
		//FreeGuide.log.info("startElement " + name + " START");
		
		saxLoc+=":"+name;
	
		if(doingProgs && saxLoc.equals(":tv:programme")) {
	    
			//assert currentProgramme == null;
			
			currentProgramme = new FreeGuideProgramme();
			
			// Prepare a date formatter
			SimpleDateFormat fmt = new SimpleDateFormat("yyyyMMddHHmmss z");
			
			// Prepare GregorianCalendars for start and end
			Calendar start = GregorianCalendar.getInstance();
			Calendar end = GregorianCalendar.getInstance();
			
			// Assume it has a channel
			String channelID = attrs.getValue("channel");
			currentProgramme.setChannelID(channelID);
			currentProgramme.setChannelName(getChannelName(channelID));
			
			try {
			
				// Assume it has a start time
				start.setTime(fmt.parse(attrs.getValue("start")));
						
				// Could really assume it has an end time, since it's gone through
				// tv_split, but anyway, don't.
				if(attrs.getIndex("stop") != -1) {
					end.setTime(fmt.parse(attrs.getValue("stop")));
				} else {
					// Give it a fake end time, half an hour after the start
					end.setTimeInMillis(start.getTimeInMillis());
					end.add(Calendar.MINUTE, 30);
				}
				
			} catch(java.text.ParseException e) {
				e.printStackTrace();
			}
			
			// Check whether the time is outside our time range
			/*
			 * No longer allow programmes to affect start/end times
			if(earliest.after(start)) {
				earliest.setTimeInMillis(start.getTimeInMillis());
			}
			if(latest.before(end)) {
				latest.setTimeInMillis(end.getTimeInMillis());
			}*/
			
			currentProgramme.setStart(start);
			currentProgramme.setEnd(end);
	    
		} else if(saxLoc.equals(":tv:channel")) {
			
			String id = attrs.getValue("id");
			
			tmpChannelID = id;
			
		}//if
		
		//FreeGuide.log.info("startElement END");
		
    }//startElement
    
    public void endElement(String name) {
		
		//FreeGuide.log.info("endElement " + name + " START");
		
		if(saxLoc.equals(":tv:programme")) {
			programmes.add(currentProgramme);
			currentProgramme = null;
		}
		
		if(saxLoc.endsWith(name)) {
	    
			saxLoc=saxLoc.substring(0, saxLoc.length()-(name.length()+1));
	    
		} else {
			parseError();
		}//if
	
		//FreeGuide.log.info("endElement END");
		
    }//endElement
    
    public void characters(String data) {
	
		//FreeGuide.log.info("characters "+ data + " START");
		
		if(doingProgs && saxLoc.equals(":tv:programme:title")) {
	    
			currentProgramme.setTitle(data);
	    
		} else if (doingProgs && saxLoc.equals(":tv:programme:desc")) {
	    
			currentProgramme.setDesc(data);
	    
		} else if (doingProgs && saxLoc.equals(":tv:programme:category")) {
	    
			currentProgramme.setCategory(data);
	    
		} else if (saxLoc.equals(":tv:channel:display-name")) {
			
			// Remember the name of the channel we're looking at
			
			// Get the channelIDs into a Vector
			Vector tmpChannelIDs = new Vector(Arrays.asList(channelIDs));
			
			// If it's a channel we're interested in
			// and it's not been named already, remember the name
			int i = tmpChannelIDs.indexOf(tmpChannelID);
			if(i!=-1 && !channelNamed[i]) {
				channelNames[i] = data;
				channelNamed[i] = true;
			}
			
		}//if
	
		//FreeGuide.log.info("characters END");
		
    }//characters
    
	/**
	 * Unhides this window after being hidden while launching another
	 * screen.
	 */
	public void reShow() {
		
		updatePanel();
		
	}//reShow
	
	//------------------------------------------------------------------------
	// Helper functions
	
	/**
	 * Gets the channels required from the config file and puts them
	 * in the channelNames array
	 */
    private void getSelectedChannels() {
		
		// Get the channel IDs from config file or prefs
		channelIDs = FreeGuide.prefs.getChannelIDs();
		
		// Set default channel names, same as IDs
		channelNames = new String[channelIDs.length];
		channelNamed = new boolean[channelIDs.length];
		for(int i=0;i<channelIDs.length;i++) {
			channelNames[i] = channelIDs[i];
			channelNamed[i] = false;
		}
		
    }
	
	/**
	 * Returns the name of the channel whose ID is supplied.
	 */
	private String getChannelName(String channelID) {
		
		// Get the channelIDs into a Vector
		Vector tmpChannelIDs = new Vector();
		tmpChannelIDs.addAll(Arrays.asList(channelIDs));
		
		// If the ID exists
		int i = tmpChannelIDs.indexOf(tmpChannelID);
		if(i != -1) {
			return channelNames[i];
		} else {
			FreeGuide.log.warning("Unknown channel ID in request for channel name.");
			return "Unknown Channel";
		}
		
	}
	
	public String[] getChannelIDs() {
		return channelIDs;
	}
	
	public String[] getChannelNames() {
		return channelNames;
	}
	
    private void parseError() {
		FreeGuide.log.severe("FreeGuideViewer - Error parsing XML.");
		System.exit(1);
    }
	
	public FreeGuideLauncher getLauncher() {
		return launcher;
	}
	
//parseError


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comTheDate;
    private javax.swing.JMenuItem menCustomiser;
    private javax.swing.JMenuItem menDownload;
    private javax.swing.JEditorPane printedGuideArea;
    private javax.swing.JMenu actionsMenu;
    private javax.swing.JMenuItem menUserGuide;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator3;
    private FreeGuideTimePanel timePanel;
    private javax.swing.JMenuItem menPrint;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel channelNamePanel;
    private javax.swing.JMenuItem menAddFav;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton butPrint;
    private javax.swing.JPanel topLeftPanel;
    private javax.swing.JMenuItem menOptions;
    private javax.swing.JScrollPane channelNameScrollPane;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JMenuItem menFavourites;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JButton butRevertFavs;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem menAbout;
    private javax.swing.JButton butNext;
    private javax.swing.JButton butPrev;
    private javax.swing.JButton butGoToNow;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JScrollPane innerScrollPane;
    private javax.swing.JPopupMenu popProg;
    private javax.swing.JPanel outerPanel;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem menChannels;
    private javax.swing.JScrollPane printedGuideScrollPane;
    private javax.swing.JMenuItem menQuit;
    private javax.swing.JScrollPane timeScrollPane;
    private javax.swing.JMenu helpMenu;
    // End of variables declaration//GEN-END:variables
    
	
	private String[] channelIDs;
		// The IDs of the channels the user has chosen
    private String[] channelNames;
		// The names of the channels the user has chosen
	private boolean[] channelNamed;
		// Has this channel had its name set?
    
    private String saxLoc;  // Holds our current pos in the XML hierarchy

	private boolean doingProgs;	// Are we loading the programmes?
    
    private Calendar earliest;  // The beginning of this day
    private Calendar latest;    // The end of this day
    
    private Calendar theDate;   // The date for which we are listing programmes
    
    private Vector textAreas;	// Stores references to all the textareas shown
    private Vector programmes;	// The programmes to which each checkbox refers
	private Vector tickedProgrammes;	// Which programmes are chosen?
	private FreeGuideProgramme currentProgramme;
		// The programme we're loading in now
    
	private FreeGuideLauncher launcher;	// The screen that launched this one
	
	private String tmpChannelID;	// A temporary variable storing the channel ID
	
	private static final SimpleDateFormat comboBoxDateFormat = new SimpleDateFormat("dd MMMM yyyy");
	private static final SimpleDateFormat htmlDateFormat = new SimpleDateFormat("EEEE dd MMMM yyyy");
	private static final SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
	private static final SimpleDateFormat fileDateFormat = new SimpleDateFormat("yyyyMMdd");
	
	private boolean missingFiles;	// true if there were files missing
	private boolean dontDownload;	// true if user doesn't want to download missing files
	
	private FreeGuideProgramme rightClickedProg;
		// The programme the user last right clicked on
	
}
