.TH freeguide "1" "July 2004" "freeguide 0.8" "User Commands"
.SH NAME
freeguide \- display TV listings
.SH SYNOPSIS
.B freeguide
.br
.B freeguide --install
.I setting ...
.br
.B freeguide --uninstall
.br
.B freeguide --prefs
.I setting ...
.br
.B freeguide --wipeprefs
.br 
.B java \fI-jar /usr/share/freeguide/FreeGuide.jar\fR 
.SH DESCRIPTION
Display TV listings.  Run the program with no arguments to launch the main window.  Open the "Help" menu and choose "User Guide" for more information.
.SH OPTIONS
.IP --install
Save the supplied settings into the system-wide preferences.  
.I setting
should be the form "key=value".  Settings are stored in the Java preferences system under the node org/freeguide-tv.
.IP --uninstall
Remove all the system-wide settings from the org/freeguide-tv node.
.IP --prefs
Save the supplied settings into the current user's preferences.  
.I setting
should be the form "key=value".  Settings are stored in the Java preferences system under the node org/freeguide-tv.
.IP --wiperefs
Remove all the current user's settings from the org/freeguide-tv node.
.SH AUTHOR
Written by Andy Balaam and the FreeGuide contributors.

This manual page was written by Shaun Jackman <sjackman@debian.org>.
.SH "REPORTING BUGS"
Report bugs to <freeguide-tv-devel@lists.sourceforge.net>.
.SH COPYRIGHT
Copyright 2001-2004 by Andy Balaam and the FreeGuide contributors

This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
http://freeguide-tv.sourceforge.net

The user guide, which may be accessed from the "Help" menu within the program.

