#!/bin/sh
STARTUP_JAR=__ANT_INSTALL_DIRECTORY__/startup.jar
# Load default settings from config file (if it exists)
if [ -f "$HOME/.freeguiderc" ]; then
	. "$HOME/.freeguiderc"
fi
if [ -z "$JAVACMD" ]; then
	JAVACMD=java
fi
$JAVACMD $FREEGUIDE_OPTS -jar $STARTUP_JAR \
    --doc_directory "__ANT_DOC_DIRECTORY__" --install_directory "__ANT_INSTALL_DIRECTORY__" "$@"

