import java.util.*;
import javax.swing.*;
/*
 * FreeGuideChannelSetEditor.java
 *
 * Created on December 29, 2002, 4:54 PM
 */

/**
 *
 * @author  dtorok
 */
public class FreeGuideChannelSetEditor extends javax.swing.JFrame {
    
    /** Creates new form FreeGuideChannelSetEditor */
    public FreeGuideChannelSetEditor(FreeGuideLauncher launcher, XMLTVLoader loader, FreeGuideChannelSetImpl chset) {
       
                this.launcher = launcher;
		this.loader = loader;
                this.channelset = chset;
                this.allModel = new DefaultListModel();
                this.csetModel = new DefaultListModel();
		
		initComponents();
		fillData();
		
    }
    
    private void fillData()
    {
        Vector chnames = this.loader.getChannelNames();
        Vector chids = this.loader.getChannelIDs();
        allModel.removeAllElements();
        csetModel.removeAllElements();
        Vector csetnames = channelset.getChannelNames();
        //get channels, put in left
        for (int i = 0; i < chnames.size(); i++)
        {
            if (!csetnames.contains(chnames.elementAt(i)))
                allModel.addElement(chnames.elementAt(i));
        }
        // if existing set, do name and right channels
        
        for (int j = 0; j < csetnames.size(); j++)
        {
            csetModel.addElement(csetnames.elementAt(j));
        }
        
        nameTextField.setText(channelset.getChannelSetName());
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        allchannelsJList = new javax.swing.JList(allModel);
        jScrollPane2 = new javax.swing.JScrollPane();
        channelsetJList = new javax.swing.JList(csetModel);
        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        moveUpButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 600));
        allchannelsJList.setMinimumSize(new java.awt.Dimension(100, 600));
        allchannelsJList.setVisibleRowCount(20);
        jScrollPane1.setViewportView(allchannelsJList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 0.9;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(100, 600));
        channelsetJList.setMinimumSize(new java.awt.Dimension(100, 600));
        channelsetJList.setVisibleRowCount(20);
        channelsetJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                channelsetListChanged(evt);
            }
        });

        jScrollPane2.setViewportView(channelsetJList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 0.9;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        addButton.setText("Add to Set    >>");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(addButton, gridBagConstraints);

        removeButton.setText("<<   Remove from Set");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanel1.add(removeButton, gridBagConstraints);

        moveUpButton.setText("Move Up");
        moveUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonAction(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(moveUpButton, gridBagConstraints);

        moveDownButton.setText("Move Down");
        moveDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(moveDownButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(153, 60));
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jPanel2.add(saveButton, new java.awt.GridBagConstraints());

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel2.add(cancelButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(400, 80));
        jLabel1.setText("Edit Channel Set");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 0.4;
        jPanel3.add(jLabel1, gridBagConstraints);

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setText("Channel Set Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(nameLabel, gridBagConstraints);

        nameTextField.setText("channelsettext");
        nameTextField.setMinimumSize(new java.awt.Dimension(200, 20));
        nameTextField.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(nameTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void channelsetListChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_channelsetListChanged
        checkUpAndDownButtons();
    }//GEN-LAST:event_channelsetListChanged

    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
         int[] selected=channelsetJList.getSelectedIndices();
	    for (int i=0;i<selected.length;i++)
	    {
		int oldIndex=selected[i];
		if (oldIndex<csetModel.getSize()-1)
		{
		    int newIndex=oldIndex+1;
		    csetModel.insertElementAt(csetModel.remove(oldIndex), newIndex);
		    channelsetJList.setSelectedIndex(newIndex);
		}
	    }	   
	    checkUpAndDownButtons();
    }//GEN-LAST:event_downButtonActionPerformed

    private void upButtonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonAction
        int[] selected=channelsetJList.getSelectedIndices();
	    for (int i=0;i<selected.length;i++)
	    {
		int oldIndex=selected[i];
		if (oldIndex>0)
		{
		    int newIndex=oldIndex-1;
		    csetModel.insertElementAt(csetModel.remove(oldIndex), newIndex);
		    channelsetJList.setSelectedIndex(newIndex);
		}		    
	    }
	    checkUpAndDownButtons();
    }//GEN-LAST:event_upButtonAction

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int[] selected=channelsetJList.getSelectedIndices();
	
        for (int i=0;i<selected.length;i++)
	    {
		//Object o=allModel.remove(selected[i]);
		allModel.addElement(csetModel.elementAt(selected[i]));
	    }
           
            for (int j=selected.length - 1; j>= 0; j--)
	    {
		Object o=csetModel.remove(selected[j]);
	    }
        checkUpAndDownButtons();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //take selected item in source and move it into sink
	    int[] selected=allchannelsJList.getSelectedIndices();
	    for (int i=0;i<selected.length;i++)
	    {
		//Object o=allModel.remove(selected[i]);
		csetModel.addElement(allModel.elementAt(selected[i]));
	    }
           
            for (int j=selected.length - 1; j>= 0; j--)
	    {
		Object o=allModel.remove(selected[j]);
	    }
            checkUpAndDownButtons();
            
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        quit();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        updateChannelSet(); 
        quit();
    }//GEN-LAST:event_saveButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        quit();
    }//GEN-LAST:event_exitForm
    
     private void checkUpAndDownButtons()
     {
	int[] selected=channelsetJList.getSelectedIndices();
	boolean enableUp=false;
	boolean enableDown=false;
	int max=csetModel.getSize()-1;
	for (int i=0;i<selected.length;i++)
	{
	    int index=selected[i];
	    if (index>0) enableUp=true;
	    if (index<max) enableDown=true;
	    if (enableUp && enableDown) break;
	}
	moveUpButton.setEnabled(enableUp);
	moveDownButton.setEnabled(enableDown);
    }
     
    private void updateChannelSet()
    {
        channelset.setChannelSetName(this.nameTextField.getText());
        // get selected items
        Object [] chosen = csetModel.toArray();
        Vector chnames = this.loader.getChannelNames();
        Vector chids = this.loader.getChannelIDs();
        this.channelset.clearChannels();
        for (int i = 0; i < chosen.length; i++)
        {
            String chname = (String)chosen[i];
            int ind = chnames.indexOf(chname);
            if (ind >= 0) {
                this.channelset.addChannelName((String)chids.elementAt(ind), chname);
            }
            
        }
     
        
    }
    private void quit() {
		
		setVisible(false);
		launcher.reShow();
		dispose();
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList channelsetJList;
    private javax.swing.JList allchannelsJList;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton moveDownButton;
    private javax.swing.JButton moveUpButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton addButton;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
    private FreeGuideLauncher launcher;
    private XMLTVLoader loader;
    private FreeGuideChannelSetImpl channelset;
    /**
     * internal list models for the two JLists
     */
    private DefaultListModel allModel, csetModel;
}
