#!/bin/bash

# I call this script (_not_ as root) from within this directory
# to build the FreeGuide RPMs and SRPMs.  It builds the rpms in $HOME/.rpm

RPM_TOPDIR=$HOME/.rpm
FG_TOPDIR=../../../..
BUILDRPM_DIR=`pwd`

cd $FG_TOPDIR

# Clean
#ant clean
rm -f $RPM_TOPDIR/RPMS/noarch/freeguide-*.rpm
rm -f $RPM_TOPDIR/SRPMS/freeguide-*.rpm
rm -f $RPM_TOPDIR/SOURCES/freeguide-*.tar.gz
rm -rf $RPM_TOPDIR/BUILD/freeguide-*
rm -rf $RPM_TOPDIR/tmp/*

# Build the source package and the spec files
#ant source-all
#ant dist-rpm-init

# Copy in the newly-built source package
echo cp -f dist/src/freeguide-*.tar.gz $RPM_TOPDIR/SOURCES/
cp -f dist/src/freeguide-*.tar.gz $RPM_TOPDIR/SOURCES/

# Build the RPMs, in the right order
cd $BUILDRPM_DIR
#SPECS="freeguide-base.spec freeguide-*-*.spec freeguide.spec"
SPECS="freeguide-allinone.spec"

for SPEC in $SPECS; do {
    echo $ rpmbuild --quiet --define="_topdir $RPM_TOPDIR" --define="_tmppath $RPM_TOPDIR/tmp" -ba $SPEC
    rpmbuild --quiet --define="_topdir $RPM_TOPDIR" --define="_tmppath $RPM_TOPDIR/tmp" -ba $SPEC
}; done

# Copy the RPMs into my "dist" directory ready for upload
mkdir -p $FG_TOPDIR/dist/rpm/
cp $RPM_TOPDIR/RPMS/noarch/freeguide-*.rpm $FG_TOPDIR/dist/rpm/
mkdir -p $FG_TOPDIR/dist/src/
cp $RPM_TOPDIR/SRPMS/freeguide-*.rpm $FG_TOPDIR/dist/src/

