#!/bin/bash

cd $1

# Remove extra files
rm -f lib/AskTk.pm lib/AskTerm.pm

# Patch the existing source
patch -p0 < ../tkgui.diff

# Add in new source files
mkdir lib/Ask
mkdir lib/ProgressBar
mkdir grab/uk_bleb

XMLTVTKGUIDIR=~/code/xmltv-tkgui-bleb

cp $XMLTVTKGUIDIR/lib/Ask/*.pm lib/Ask/
cp $XMLTVTKGUIDIR/lib/ProgressBar/*.pm lib/ProgressBar/
cp $XMLTVTKGUIDIR/lib/GUI.pm lib/
cp $XMLTVTKGUIDIR/lib/ProgressBar.pm lib/
cp $XMLTVTKGUIDIR/grab/uk_bleb/tv_grab_uk_bleb grab/uk_bleb/


