/*
 *  FreeGuide J2
 *
 *  Copyright (c) 2001-2003 by Andy Balaam and the FreeGuide contributors
 *
 *  freeguide-tv.sourceforge.net
 *
 *  Released under the GNU General Public License
 *  with ABSOLUTELY NO WARRANTY.
 *
 *  See the file COPYING for more information.
 */

import java.awt.Color;
import java.awt.Font;
import java.awt.*;
import javax.swing.*;

/**
 *  Tell the about their privacy in FreeGuide
 *
 *@author     Andy Balaam
 *@created    5th December 2003
 *@version    1
 */
public class PrivacyInfoDialog extends JDialog {

    /**
     * Constructor which sets the customiser up as a JDialog...
     *
     */
    public PrivacyInfoDialog() {
        super();
		setTitle("Privacy Information");
		setModal(true);
        
        initComponents();
    }


    /**
     *  This method is called from within the constructor to initialize the
     *  form. WARNING: Do NOT modify this code. The content of this method is
     *  always regenerated by the Form Editor.
     */
    private void initComponents() {
		
        java.awt.GridBagConstraints gridBagConstraints;

		JEditorPane infoPane;
		JButton OKButton;
		
		infoPane = new JEditorPane();
		OKButton = new JButton();
		
		infoPane.setText( "<title>Hello</title><p>Hello para</p>" );
		
		OKButton.setText( "OK" );
		
		Container pane = getContentPane();
		
		pane.setLayout( new java.awt.GridBagLayout() );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weighty = 1;
        pane.add(infoPane, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		gridBagConstraints.weighty = 0;
        pane.add(OKButton, gridBagConstraints);
		
        OKButton.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    OKButtonActionPerformed(evt);
                }
            });

		getRootPane().setDefaultButton( OKButton );
			
		pack();  // pack comes before the size instructions or they get ignored.
		
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();		
        setLocation((screenSize.width - getWidth()) / 2, (screenSize.height - getHeight()) / 2);
		
  }

    /**
     *  
     *
     *@param  evt  
     */
    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {
		
        quit();
    }
  
    /**
     *  Description of the Method
     *
     *@param  evt  Description of the Parameter
     */
    private void exitForm(java.awt.event.WindowEvent evt) {
        quit();
    }

    /**
     *  Closes the form and goes back to the viewer.
     */
    private void quit() {

        dispose();

    }

}
