/*
 * FreeGuide J2
 *
 * Copyright (c) 2001 by Andy Balaam
 *
 * Released under the GNU General Public License
 * with ABSOLUTELY NO WARRANTY.
 *
 * See the file COPYING for more information.
 */

import java.awt.Graphics;
import java.util.Date;
import java.awt.Dimension;

/**
 * A panel that displays a ruler-like time line.
 *
 * @author  Andy Balaam
 * @version 1
 */
public class FreeGuideTimePanel extends javax.swing.JPanel {

	/** Creates new form FreeGuideTimePanel */
    public FreeGuideTimePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
	private void initComponents() {//GEN-BEGIN:initComponents
		
		setLayout(new java.awt.BorderLayout());
		
		setBackground(java.awt.Color.lightGray);
	}//GEN-END:initComponents

	public void paintComponent(Graphics g) {
		
		super.paintComponent(g);
		
		Dimension s = this.getSize();
		
		//Find each hour and mark
		//Find each half hour and mark
		//Find each 10 mins and mark
		
	}

	public void setTimes(Date newStartTime, Date newEndTime) {
		
		startTime = new Date(newStartTime.getTime());
		endTime = new Date(newEndTime.getTime());
		
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables

	private Date startTime;	// The time on the left hand side of the panel
	private Date endTime;	// The time on the right hand side of the panel
	
}
